/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */

// @ts-check

/** @type {import('@docusaurus/plugin-content-docs').SidebarsConfig} */
const sidebars = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // autogeneratedSidebar: [{type: 'autogenerated', dirName: '.'}],
  '欢迎': [{type: 'autogenerated', dirName: '00-首页'}],
  Java: [{type: 'autogenerated', dirName: '01-编程/Java'}],
  Python: [{type: 'autogenerated', dirName: '01-编程'}],
  '竞赛': [{type: 'autogenerated', dirName: '02-竞赛'}],
  '作业': [{type: 'autogenerated', dirName: '03-作业'}],
  // '生存指南': [{type: 'autogenerated', dirName: '04-生存指南'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

module.exports = sidebars;
