import type {SidebarsConfig} from '@docusaurus/plugin-content-docs';

/**
 * Creating a sidebar enables you to:
 - create an ordered group of docs
 - render a sidebar for each doc of that group
 - provide next/previous navigation

 The sidebars can be generated from the filesystem, or explicitly defined here.

 Create as many sidebars as you want.
 */
const sidebars: SidebarsConfig = {
  // By default, Docusaurus generates a sidebar from the docs folder structure
  // autogeneratedSidebar: [{type: 'autogenerated', dirName: '.'}],
  '欢迎': [{type: 'autogenerated', dirName: '01-首页'}],
  '开发': [{type: 'autogenerated', dirName: '02-开发'}],
  '运行维护': [{type: 'autogenerated', dirName: '03-运行维护'}],
  '信息安全': [{type: 'autogenerated', dirName: '04-信息安全'}],
  '竞赛': [{type: 'autogenerated', dirName: '10-竞赛'}],
  '课程': [{type: 'autogenerated', dirName: '11-课程'}],
  // '慧通九职': [{type: 'autogenerated', dirName: '20-慧通九职'}],
  // '生存指南': [{type: 'autogenerated', dirName: '30--生存指南'}],

  // But you can create a sidebar manually
  /*
  tutorialSidebar: [
    'intro',
    'hello',
    {
      type: 'category',
      label: 'Tutorial',
      items: ['tutorial-basics/create-a-document'],
    },
  ],
   */
};

export default sidebars;
